### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by ahmaddxb** [bsherman/netmaker-traefik#3]
Is this line a mistake

- traefik.http.middlewares.nmui-security.headers.accessControlAllowOriginList=*.$${NM.BASE_DOMAIN}

should it be?

- traefik.http.middlewares.nmui-security.headers.accessControlAllowOriginList=*.${NM_BASE_DOMAIN}

**Comment by bsherman** [comment]
Yes, @ahmaddxb , that was a typo, and it's been fixed as of today.
