### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ahmaddxb** [bsherman/netmaker-traefik#5]
Remove extra $ in *.$${NM_BASE_DOMAIN}
- traefik.http.middlewares.nmui-security.headers.accessControlAllowOriginList=*.$${NM_BASE_DOMAIN}

Corrected
- traefik.http.middlewares.nmui-security.headers.accessControlAllowOriginList=*.${NM_BASE_DOMAIN}

**Comment by bsherman** [comment]
Thanks for the report! Fixed!
